name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: Run Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform  # Se especifica la carpeta de Terraform

      - name: Terraform Format Check
        run: terraform fmt -check
        working-directory: ./terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan
        working-directory: ./terraform

      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply -auto-approve tfplan
        working-directory: ./terraform
        
      - name: Get Terraform Outputs
        id: terraform_outputs
        run: terraform output -json > outputs.json
        working-directory: ./terraform

      - name: List files after terraform output
        run: ls -la ./terraform

      - name: Verify Terraform Outputs
        run: terraform output
        working-directory: ./terraform

      - name: Set Secrets (EC2 Instance ID and SSH Keys)
        run: |
          if [ -f outputs.json ]; then
              INSTANCE_ID=$(jq -r '.ec2_instance_id.value' < outputs.json)
              echo "Setting EC2 instance ID as a secret..."
              gh secret set EC2_INSTANCE_ID --body "$INSTANCE_ID"
      
              if jq -e '.ssh_private_key.value' < outputs.json > /dev/null; then
                  echo "SSH_PRIVATE_KEY=$(jq -r .ssh_private_key.value < outputs.json)" >> $GITHUB_ENV
                  echo "Setting SSH private key secret..."
                  gh secret set SSH_PRIVATE_KEY --body "$SSH_PRIVATE_KEY"
              fi
      
              if jq -e '.ssh_public_key.value' < outputs.json > /dev/null; then
                  echo "SSH_PUBLIC_KEY=$(jq -r .ssh_public_key.value < outputs.json)" >> $GITHUB_ENV
                  gh secret set SSH_PUBLIC_KEY --body "$SSH_PUBLIC_KEY"
              fi
          else
              echo "Error: outputs.json not found."
              exit 1
          fi
        working-directory: ./terraform

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

